
CREATE DATABASE DUAN1
GO
USE DUAN1
GO
IF OBJECT_ID ('STUDENTS') IS NOT NULL
DROP TABLE STUDENTS
GO
CREATE TABLE STUDENTS 
(
SVID NVARCHAR(10) NOT NULL,
NAMES NVARCHAR(50) NULL,
CONSTRAINT PK_STUDENTS PRIMARY KEY(SVID)
)
IF OBJECT_ID ('USERS') IS NOT NULL
DROP TABLE USERS
GO
CREATE TABLE USERS
(
USERID NVARCHAR(50) NOT NULL,
PASS NVARCHAR(10) NOT NULL
CONSTRAINT PK_USERS PRIMARY KEY (USERID)
) 
IF OBJECT_ID ('CLASSES') IS NOT NULL
DROP TABLE CLASSES 
GO 
CREATE TABLE CLASSES
(
CLASSID NVARCHAR(10) NOT NULL,
NAMECLASS NVARCHAR(10) NULL,
USERID NVARCHAR(50) NOT NULL,
TIMES DATETIME NULL,
CONSTRAINT PK_LOP PRIMARY KEY(CLASSID),
CONSTRAINT PK_USERS_CLASS FOREIGN KEY (USERID) REFERENCES USERS(USERID),
)
IF OBJECT_ID ('STCL') IS NOT NULL
DROP TABLE STCL 
GO
CREATE TABLE STCL
(
SVID NVARCHAR(10) NOT NULL,
CLASSID NVARCHAR(10) NOT NULL,
TRANGTHAI BIT NULL,
CONSTRAINT PK_STUDENTS_STCL FOREIGN KEY (SVID) REFERENCES STUDENTS(SVID),
CONSTRAINT PK_CLASS_STCL FOREIGN KEY (CLASSID) REFERENCES CLASSES(CLASSID)
)