CREATE DATABASE QLDSTHI
IF OBJECT_ID ('SINHVIEN') IS NOT NULL
DROP TABLE SINHVIEN
GO
CREATE TABLE SINHVIEN 
(
MASV NVARCHAR(10) NOT NULL,
HOTEN NVARCHAR(50) NULL,
CONSTRAINT PK_SINHVIEN PRIMARY KEY(MASV)
)
IF OBJECT_ID ('MUSER') IS NOT NULL
DROP TABLE MUSER
GO
CREATE TABLE MUSER
(
MAUSER NVARCHAR(50) NOT NULL,
MATKHAU NVARCHAR(10) NOT NULL
CONSTRAINT PK_USER PRIMARY KEY (MAUSER)
) 
IF OBJECT_ID ('LOP') IS NOT NULL
DROP TABLE LOP 
GO 
CREATE TABLE LOP
(
MALOP NVARCHAR(10) NOT NULL,
TENLOP NVARCHAR(10) NULL,
MAUSER NVARCHAR(50) NOT NULL,
THOIGIAN DATETIME NULL,
CONSTRAINT PK_LOP PRIMARY KEY(MALOP),
CONSTRAINT PK_MUSER_LOP FOREIGN KEY (MAUSER) REFERENCES MUSER(MAUSER),
)
IF OBJECT_ID ('SVL') IS NOT NULL
DROP TABLE SVL 
GO
CREATE TABLE SVL
(
MASV NVARCHAR(10) NOT NULL,
MALOP NVARCHAR(10) NOT NULL,
TRANGTHAI BIT NULL,
CONSTRAINT PK_SINHVIEN_SVL FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
CONSTRAINT PK_LOP_SVL FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
)
SELECT * FROM SINHVIEN
INSERT SINHVIEN VALUES('PH11599',N'LÊ VĂN QUÂN')
INSERT SINHVIEN VALUES('PH11672',N'NGUYỄN XUÂN PHÚC')
INSERT SINHVIEN VALUES('PH11872',N'HỒ VIẾT THÀNH')
SELECT * FROM LOP
INSERT LOP VALUES ('PT15308',N'ỨNG DỤNG','QUANLV11599','2020-08-16')
INSERT LOP VALUES ('PT16371',N'THIẾT KẾ','PHUCNX11672','2021-09-23')
INSERT LOP VALUES ('PT15307','WEB','THANHHV11872','2020-10-24')
SELECT * FROM SVL
INSERT SVL VALUES ('PH11599','PT15308',1)
INSERT SVL VALUES ('PH11672','PT16371',0)
INSERT SVL VALUES ('PH11872','PT15307',1)
SELECT * FROM MUSER
INSERT MUSER VALUES ('QUANLV11599','QUAN1')
INSERT MUSER VALUES ('PHUCNX11672','PHUC1')
INSERT MUSER VALUES ('THANHHV11872','THANH1')