/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Service.SVcheckdk;
import Service.SVinput;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Diem;
import model.Lop;
import model.Sinhvien;

/**
 *
 * @author dell
 */
public class Formkehoach extends JInternalFrame {

    DefaultTableModel tbmodel = new DefaultTableModel();

    /**
     * Creates new form Formkehoach
     */
    public Formkehoach() {
        initComponents();
        loadtbok();
        loadtbNg();
    }

    static Lop _lop1 = new Lop();
    static List<Sinhvien> _lstSV = new ArrayList<>();
//    static List<Diem> _lstDiems = new ArrayList<>();

    public static void getlop(Lop x) {
        _lop1 = x;
    }

    public static void getlstsv(List<Sinhvien> lstsv) {
        _lstSV = lstsv;
    }

//    public static void getlstdiem(List<Diem> lst) {
//        _lstDiems = lst;
//    }

    private void loadtbok() {
        tbmodel = (DefaultTableModel) tbdudk.getModel();
        tbmodel.setRowCount(0);
        int i = 1;
        for (Sinhvien x : _lstSV) {
            if (x.isCheckfalse()) {
                tbmodel.addRow(new Object[]{i++, x.getMasv(), x.getTensv(), x.getTrangthai()});
            }
        }
    }

    private void loadtbNg() {
        tbmodel = (DefaultTableModel) tbtruot.getModel();
        tbmodel.setRowCount(0);
        int j = 1;
        for (Sinhvien x : _lstSV) {
            if (x.isCheckfalse() == false) {
                tbmodel.addRow(new Object[]{j++, x.getMasv(), x.getTensv(), x.getTrangthai()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabtb = new javax.swing.JTabbedPane();
        pndiemquiz = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdudk = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbtruot = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabtb.setBackground(new java.awt.Color(204, 255, 255));
        tabtb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        pndiemquiz.setBackground(new java.awt.Color(255, 255, 255));

        tbdudk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbdudk);

        javax.swing.GroupLayout pndiemquizLayout = new javax.swing.GroupLayout(pndiemquiz);
        pndiemquiz.setLayout(pndiemquizLayout);
        pndiemquizLayout.setHorizontalGroup(
            pndiemquizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        pndiemquizLayout.setVerticalGroup(
            pndiemquizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pndiemquizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
        );

        tabtb.addTab("Danh sách đủ điều kiện thi", pndiemquiz);

        tbtruot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbtruot);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
        );

        tabtb.addTab("Danh sách không đủ điều kiện thi", jPanel2);

        getContentPane().add(tabtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 990, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formkehoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formkehoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formkehoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formkehoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formkehoach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pndiemquiz;
    private javax.swing.JTabbedPane tabtb;
    private javax.swing.JTable tbdudk;
    private javax.swing.JTable tbtruot;
    // End of variables declaration//GEN-END:variables
}
