/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.User;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JPasswordField;

import dao.DbUserDAO;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {
	User user = null;

	/**
	 * Creates new form Login
	 */
	public Login() {
		setTitle("Login");
		this.setLocationRelativeTo(null);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lblUsername = new javax.swing.JLabel();
		lblPassword = new javax.swing.JLabel();
		txtUsername = new javax.swing.JTextField();
		btnLogin = new javax.swing.JButton();
		btnQuit = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lblUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		lblUsername.setText("Tài khoản:");

		lblPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		lblPassword.setText("Mật khẩu:");

		btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnLogin.setText("Đăng nhập");
		btnLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnLoginActionPerformed(evt);
			}
		});

		btnQuit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnQuit.setText("Thoát");
		btnQuit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQuitActionPerformed(evt);
			}
		});

		txtPassword = new JPasswordField();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addGap(82)
				.addGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
						.addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE).addGap(18)
						.addComponent(btnQuit, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(lblUsername)
										.addComponent(lblPassword))
								.addGap(18)
								.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
										.addComponent(txtPassword, Alignment.LEADING).addComponent(txtUsername,
												Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))
				.addContainerGap(88, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addGap(64)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(lblUsername).addComponent(
						txtUsername, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(lblPassword).addComponent(
						txtPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(36)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(btnLogin).addComponent(btnQuit))
				.addContainerGap(44, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		if (JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn thoát?", "Thoát?",
				JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
			System.exit(0);
	}

	private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		String username = txtUsername.getText();
		String password = new String(txtPassword.getPassword());
		if (username.isBlank()) {
			JOptionPane.showMessageDialog(rootPane, "Tài khoản không được trống");
		} else {
			DbUserDAO dbuser = new DbUserDAO();
			try {
				System.out.println(password);
				User tempuser = dbuser.getById(username);
				if (tempuser != null) {
					System.out.println(tempuser.getPassword());
					if (tempuser.getPassword().equalsIgnoreCase(password)) {
						user = tempuser;
						this.setVisible(false);
					}					
				}
				JOptionPane.showMessageDialog(rootPane, "Sai tài khoản/mật khẩu");

			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLogin;
	private javax.swing.JButton btnQuit;
	private javax.swing.JLabel lblUsername;
	private javax.swing.JLabel lblPassword;
	private javax.swing.JTextField txtUsername;
	private JPasswordField txtPassword;
}
