
CREATE DATABASE DUAN1
GO
USE DUAN1
GO
IF OBJECT_ID ('STUDENTS') IS NOT NULL
DROP TABLE STUDENTS
GO
CREATE TABLE STUDENTS 
(
SVID VARCHAR(10) NOT NULL,
NAMES NVARCHAR(50) NULL,
CONSTRAINT PK_STUDENTS PRIMARY KEY(SVID)
)
IF OBJECT_ID ('USERS') IS NOT NULL
DROP TABLE USERS
GO
CREATE TABLE USERS
(
USERID VARCHAR(10) NOT NULL,
PASS VARCHAR(10) NOT NULL,
Names Nvarchar(50)
CONSTRAINT PK_USERS PRIMARY KEY (USERID)
) 
IF OBJECT_ID ('CLASSES') IS NOT NULL
DROP TABLE CLASSES 
GO 
CREATE TABLE CLASSES
(
CLASSID VARCHAR(50) NOT NULL,
Mamon NVARCHAR(50) NULL,
USERID VARCHAR(10) NOT NULL,
TIMES varchar(50) NULL,
KIHOC varchar(55),
CONSTRAINT PK_LOP PRIMARY KEY(CLASSID),
CONSTRAINT PK_USERS_CLASS FOREIGN KEY (USERID) REFERENCES USERS(USERID),
)

IF OBJECT_ID ('CATHI') IS NOT NULL
DROP TABLE CATHI
GO
create table CATHI(
	maca int primary key,
	Thoigian varchar(20)
)

IF OBJECT_ID ('NGAYTHI') IS NOT NULL
DROP TABLE NGAYTHI
GO
create table NGAYTHI(
	mangay int primary key,
	ngaythi date
)

IF OBJECT_ID ('STCL') IS NOT NULL
DROP TABLE STCL 
GO
CREATE TABLE STCL
(
SVID VARCHAR(10) NOT NULL,
CLASSID VARCHAR(50) NOT NULL,
trangthai nvarchar(50),
mangaythi int,
macathi int,
phongthi varchar(15)
CONSTRAINT PK_STUDENTS_STCL PRIMARY KEY (SVID,CLASSID),
CONSTRAINT FK_STUDENTS_STCL FOREIGN KEY (SVID) REFERENCES STUDENTS(SVID),
CONSTRAINT FK_CLASS_STCL FOREIGN KEY (CLASSID) REFERENCES CLASSES(CLASSID),
CONSTRAINT FK_CLASS_CATHI FOREIGN KEY (macathi) REFERENCES CATHI(MACA),
CONSTRAINT FK_CLASS_NGAYTHI FOREIGN KEY (mangaythi) REFERENCES NGAYTHI(mangay)
)
/*insert user*/
insert USERS values('duytn','1','Nguyen Duc Duy')
	--insert cathi
insert CATHi values(0,'')
insert CATHi values(1,'07:15 - 09:15')
insert CATHi values(2,'09:25 - 11:25')
insert CATHi values(3,'12:00 - 14:00')
insert CATHi values(4,'14:10 - 16:10')
insert CATHi values(5,'16:20 - 18:20')
insert CATHi values(6,'18:30 - 20:30')

insert NGAYTHI values(0,null)

select * from STUDENTS
select * from CLASSES
select * from STCL
select * from CATHi
select * from NGAYTHI
INSERT CLASSES (CLASSID,KIHOC,TIMES,USERID) VALUES('x','','','duytn')
delete from STCL

select * from STCL
delete STCL
select STUDENTS.SVID,STUDENTS.NAMES,STCL.trangthai,STCL.phongthi,CATHI.maca,NGAYTHI.ngaythi from
STUDENTS join STCL on STUDENTS.SVID = STCL.SVID join CATHI on STCL.macathi = CATHI.maca join NGAYTHI on STCL.mangaythi = NGAYTHI.mangay
join CLASSES on STCL.CLASSID = CLASSES.CLASSID where CLASSES.CLASSID = ''

